(("src" . ((indent-tabs-mode . nil)
           (tab-width . 4)
           (fill-column . 80)
           (c-mode . ((c-basic-offset . 4)
                      (c-file-style . "BSD")))))
 ("include" . ((indent-tabs-mode . nil)
               (tab-width . 4)
               (fill-column . 80)
               (c-mode . ((c-basic-offset . 4)
                          (c-file-style . "BSD"))))))
